### ISSUE TITLE
US24 - Adicionar Planta Aos Meus Favoritos

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#106]
**Descrição:**
---

Eu como usuário quero adicionar planta aos meus favoritos para adicionar um atalho para utilizá-lo mais tarde.

**Critérios de Aceitação:**
---

- [x] O usuário deverá apertar em um botão no card de planta para adicionar a mesma aos favoritos
- [x] O sistema deverá enviar a referida planta a coleção de favoritos

**Critérios Extras:**
---

- [ ] O sistema deverá animar a ação de tocar na estrela (ou seja, na adição da planta aos favoritos)

**Comment by joaovitorml** [comment]
Issue fechada com a aceitação do PR #124
