### ISSUE TITLE
US25 - Remover Uma Planta Da Minha Coleção De Favoritos

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#107]
**Descrição:**
---

Eu como usuário quero remover uma planta da minha coleção de favoritos para remover um atalho que não uso mais.

**Critérios de Aceitação:**
---

- [x] O botão de enviar aos favoritos irá se transformar em botão de remover dos favoritos se a referida planta já estiver na coleção de favoritos
- [x] O sistema deverá remover a referida planta da coleção de favoritos

**Critérios Extras:**
---

- [ ] O sistema deverá animar a ação de tocar na estrela (ou seja, na remoção da planta dos favoritos)

**Comment by joaovitorml** [comment]
Issue fechada pois foi resolvida no PR #106
