### ISSUE TITLE
US26 - Visualizar Minha Coleção De Favoritos

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#108]
**Descrição:**
---

Eu como usuário quero visualizar minha coleção de favoritos para facilitar o processo de navegação pelas páginas que mais visito.

**Critérios de Aceitação:**
---

- [ ] O usuário poderá abrir os cards de planta diretamente da aba de favoritos
- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu Nome Comum
- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu nome científico
- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar seu status de extinção
- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar um botão que redireciona, também, ao card de planta

**Critérios Extras:**
---

- [ ] Cada widget das plantas adicionadas à coleção de favoritos deverá mostrar um botão de compartilhar (que compartilharia o link do card de planta)

**Comment by joaovitorml** [comment]
Issue fechada pois foi resolvida pelo PR #106
