### ISSUE TITLE
US27 - Alterar Informações da Minha Planta

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#109]
**Descrição:**
---

Eu como usuário quero adicionar apelido à minha planta para que eu possa distinguir uma planta de outra (caso tenha multiplas da mesma especie).

**Critérios de Aceitação:**
---

- [x] O usuário deverá adicionar um apelido a sua planta após o processo de scanneamento da mesma
- [x] O usuário poderá alterar o apelido da planta a qualquer momento em sua coleção
- [x] O sistema deverá garantir que o apelido é válido

**Critérios Extras:**
---

- [ ] O sistema deverá sugerir nomes "divertidos" (como os que são gerados pela twitch.tv no link dos clips [ex: AgreeableLazyPangolinVoteYea]) ao usuário

**Comment by joaovitorml** [comment]
Issue fechada por estar resolvida no PR #114
