### ISSUE TITLE
US28 - Definir Configurações De Notificação

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#110]
**Descrição:**
---

Eu como usuário quero definir configurações de notificação para que eu me lembre de cultivar minha planta.

**Critérios de Aceitação:**
---

- [x] O usuário deve poder configurar regras de notificação para lembrá-lo de regar/fertilizar a planta

**Critérios Extras:**
---

Não há critérios.

**Comment by joaovitorml** [comment]
Essa issue foi fechada no frontend
