### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#113]
# Descrição

Adicionar testes para todas as histórias de usuários realizadas até agora, utilizando o framework Jest

## Material de Apoio:

- Documentação oficial
  - 1. [Getting Started](https://jestjs.io/docs/en/getting-started)
  - 2. [Jest com MongoDB](https://jestjs.io/docs/en/mongodb)
  - 3. [Jest com React Native](https://jestjs.io/docs/en/tutorial-react-native)
- Outros
  - 1. [(FreeCodeCamp) How to set up Jest and Enzyme to test React Native apps](https://medium.com/free-code-camp/setting-up-jest-enzyme-for-testing-react-native-40393ca04145)
  - 2. [How to test Express.js with Jest and Supertest](https://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest/)

# Critérios de aceitação

Histórias realizadas até agora:

- [x] US22 - Upvote E Downvote Em Um Comentário
- [x] US21 - Remover Um Comentário Que Fiz Em Um Tópico
- [x] US20 - Editar Comentário Que Fiz Em Um Tópico
- [x] US19 - Criar Comentário Em Um Tópico
- [x] US18 - Upvote E Downvote Em Um Tópico
- [x] US17 - Deletar O Tópico Criado Por Mim
- [x] US16 - Editar Tópico Criado Por Mim
- [x] US15 - Criar Tópico Em Um Fórum De Planta
- [x] US29 - Visualizar informações sobre a planta
- [x] US10 - Deletar minha conta
- [x] US09 - Alterar os dados cadastrados na minha conta
- [x] US04 - Cadastrar minha conta no aplicativo

**Comment by joaovitorml** [comment]
Issue fechada pelo PR #120
