### ISSUE TITLE
Refatoração de Dependências e eslint

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-eps-mds/2020.1-Grupo2-BackEnd#121]
# Descrição

Esta issue requer refatoração de dependências e eslint do projeto.

# Objetivos

- [x] Remoção de dependências de produção não utilizadas
- [x] Remoção de dependências de desenvolvimento não utilizadas
- [x] Remoção de dependências ESLint não utilizadas
- [x] Reconfigurar ESLINT com as novas dependências

**Comment by joaovitorml** [comment]
Fechado pelo PR #122
