### ISSUE TITLE
US01 - Scannear Planta

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#83]
**Descrição:**
---

Eu como usuário quero scannear planta para adicionar à minha coleção.

**Critérios de Aceitação:**
---

- [x] O usuário poderá acessar a câmera do celular
- [x] O usuário poderá scannear a planta por meio da câmera do celular
- [x] O sistema deve identificar a planta scanneada
- [x] O sistema deve retornar ao usuário informações sobre a planta scanneada

**Critérios Extras:**
---

- [ ] O usuário deve poder decidir se deseja compartilhar com o app a foto que scanneou ou não (de forma que esta figuraria no Card daquela Planta)
- [ ] O usuário deve poder compartilhar a foto tirada em suas comunidades e linha do tempo

**Comment by joaovitorml** [comment]
Fechado porque foi resolvida pelo PR #117
