### ISSUE TITLE
US03 - Visualizar Informações Da Minha Planta

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#85]
**Descrição:**
---

Eu como usuário quero visualizar informações da minha planta para que eu saiba mais sobre ela.

**Critérios de Aceitação:**
---

- [x] Visualizar nome dado pelo usuário a essa planta
- [x] Visualizar data de quando ela foi adicionada a coleção
- [x] O usuário deve poder alterar o apelido da planta
- [x] O usuário deve poder excluir a mesma

**Critérios Extras:**
---

- [ ] O usuário deve poder re-configurar regras de notificação para lembrá-lo de regar/fertilizar a planta

**Comment by joaovitorml** [comment]
Issue fechada por ter sido concluída com o PR #114
