### ISSUE TITLE
US13 - Visualizar Perfil De Outro Usuário

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-BackEnd#95]
**Descrição:**
---

Eu como usuário quero visualizar perfil de outro usuário para que eu possa sanar minha curiosidade.

**Critérios de Aceitação:**
---

- [x] O usuário poderá visualizar o nome do outro usuário
- [x] O usuário poderá visualizar a foto de perfil do outro usuário

**Critérios Extras:**
---

Não há critérios.

**Comment by joaovitorml** [comment]
Fechada pois foi concluída pelo PR #125
